'use strict';
require('./productCtrl');
require('./productInfoCtrl');
require('./supplierCtrl');
require('./supplierInfoCtrl');
require('./orderCtrl');
require('./orderInfoCtrl');
require('./saleOrderCtrl');
require('./saleOrderInfoCtrl');
require('./reportCtrl');
require('./dashboardCtrl');